// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalFinanceTrackerAPI.Data;

#nullable disable

namespace PersonalFinanceTrackerAPI.Migrations.MigrationFinanceTrackerDb
{
    [DbContext(typeof(FinanceTrackerDbContext))]
    [Migration("20260901161733_InitialFinancePostgres")]
    partial class InitialFinancePostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalFinanceTrackerAPI.Models.AIAnalysisRunModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AgentType");

                    b.ToTable("AIAnalysisRuns", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceTrackerAPI.Models.AIInsightModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("AnalysisRunId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Insight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("Months")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Type");

                    b.ToTable("AIInsights", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceTrackerAPI.Models.AnomalyDetailModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AnomalyResultId")
                        .HasColumnType("integer");

                    b.Property<string>("AnomalyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("AverageForCategory")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DeviationPercentage")
                        .HasColumnType("double precision");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnomalyResultId");

                    b.ToTable("AnomalyDetails", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceTrackerAPI.Models.AnomalyDetectionResultModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("AnalysisRunId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HighSeverityCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("LowSeverityCount")
                        .HasColumnType("integer");

                    b.Property<int>("MediumSeverityCount")
                        .HasColumnType("integer");

                    b.Property<int>("Months")
                        .HasColumnType("integer");

                    b.Property<string>("OverallInsight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalAnomaliesFound")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("UserId");

                    b.ToTable("AnomalyDetectionResults", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceTrackerAPI.Models.BudgetGoalRecommendationItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentSpending")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RecommendedSpending")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReductionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId");

                    b.ToTable("BudgetGoalRecommendationItems", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceTrackerAPI.Models.BudgetGoalRecommendationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionPlanJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("AnalysisRunId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentMonthlySavings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentSavings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DataConfidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ExtendedTimelineNeeded")
                        .HasColumnType("integer");

                    b.Property<string>("FeasibilityLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("FeasibilityScore")
                        .HasColumnType("double precision");

                    b.Property<string>("FinalMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("IncomeGapNeeded")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("LifestyleImpact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MonthlySavingsTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Months")
                        .HasColumnType("integer");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RemainingGapAfterCuts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevisedTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SavingsGap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TargetSavings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingMethod")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("BudgetGoalRecommendations", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceTrackerAPI.Models.TransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("PersonalFinanceTrackerAPI.Models.AIInsightModel", b =>
                {
                    b.HasOne("PersonalFinanceTrackerAPI.Models.AIAnalysisRunModel", "AnalysisRun")
                        .WithMany()
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("PersonalFinanceTrackerAPI.Models.AnomalyDetailModel", b =>
                {
                    b.HasOne("PersonalFinanceTrackerAPI.Models.AnomalyDetectionResultModel", "AnomalyResult")
                        .WithMany("AnomalyDetails")
                        .HasForeignKey("AnomalyResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnomalyResult");
                });

            modelBuilder.Entity("PersonalFinanceTrackerAPI.Models.AnomalyDetectionResultModel", b =>
                {
                    b.HasOne("PersonalFinanceTrackerAPI.Models.AIAnalysisRunModel", "AnalysisRun")
                        .WithMany()
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("PersonalFinanceTrackerAPI.Models.BudgetGoalRecommendationItemModel", b =>
                {
                    b.HasOne("PersonalFinanceTrackerAPI.Models.BudgetGoalRecommendationModel", "Recommendation")
                        .WithMany("Items")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("PersonalFinanceTrackerAPI.Models.BudgetGoalRecommendationModel", b =>
                {
                    b.HasOne("PersonalFinanceTrackerAPI.Models.AIAnalysisRunModel", "AnalysisRun")
                        .WithMany()
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity("PersonalFinanceTrackerAPI.Models.AnomalyDetectionResultModel", b =>
                {
                    b.Navigation("AnomalyDetails");
                });

            modelBuilder.Entity("PersonalFinanceTrackerAPI.Models.BudgetGoalRecommendationModel", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
